export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'

export const GET_CATEGORY_RECETTES = 'GET_CATEGORY_RECETTES'
export const GET_CATEGORY_RECETTES_SUCCESS = 'GET_CATEGORY_RECETTES_SUCCESS'

export const GET_SELECTED_RECETTE = 'GET_SELECTED_RECETTE'
export const GET_SELECTED_RECETTE_SUCCESS = 'GET_SELECTED_RECETTE_SUCCESS'