export const GET_ALL_RECETTES = 'GET_ALL_RECETTES'
export const GET_ALL_RECETTES_SUCCESS = 'GET_ALL_RECETTES_SUCCESS'

export const GET_RECETTE = 'GET_RECETTE'
export const GET_RECETTE_SUCCESS = 'GET_RECETTE_SUCCESS'

export const NEW_RECETTE = 'NEW_RECETTE'

export const EDIT_RECETTE = 'EDIT_RECETTE'

export const DELETE_RECETTE = 'DELETE_RECETTE'

export const SET_LOADING = 'SET_LOADING'